improve currency and align it to center
9brada6/backbone-js pull request #2
Opened 2021-06-30 04:14 UTC by bebnev-pro

2021-06-30 04:15 UTC, bebnev-pro commented
![image](https://user-images.githubusercontent.com/5491523/123901039-ae1cd380-d983-11eb-9fcd-e5e65e9bc076.png)
is it looks better?

2021-07-04 10:31 UTC, 9brada6 requested changes
In css, change add only the following:

.sidebar{
  display: flex;
  align-item: center;
}

 and remove the absolute position. You can style next the buttons how you want.

2021-07-04 10:31 UTC, 9brada6 commented on index.html
> +      <div class="currency-wrapper">
I agree that a wrapper of the buttons is needed.

2021-07-04 10:31 UTC, 9brada6 commented on src/index.css
> +.currency-wrapper {
I don't like the position absolute, while it works, that's not how you align the items. There is no reason for the currency wrapper to be positioned absolute in your display. If you want to fix this, use flex on the sidebar:

.sidebar {
    display: flex;
    align-items: center;
}

2021-07-04 10:34 UTC, 9brada6 approved these changes

2021-07-04 10:35 UTC, 9brada6 commented
Merged changes bebnev with the absolute positioning of the buttons.

2021-07-04 10:36 UTC, merged